all_data <- read.table("Data/household_power_consumption.txt",sep = ";",header = TRUE,na.strings="?")
colnames(all_data)
all_data$Date
summary(all_data)
head(all_data)
diff(c(all_data$Date[1],all_data$Date[5000]))   
all_data$Date <- as.Date(all_data$Date, "%d/%m/%Y")
sub_data <- subset(all_data, Date == as.Date("2007-02-01") | Date == as.Date("2007-02-02"))
summary(sub_data$Date)
hist(sub_data$Global_active_power,main = "Global Active Power",xlab = "Global Active Power (kilowatts)", col = "red")
summary(sub_data$Global_active_power)
summary(sub_data$Voltage)
summary(sub_data$Global_intensity)
